export * from "./consultation";
export {
  type ProviderAttemptRawReference,
  ProviderAttemptRawReferenceSchema,
  type ProviderAttemptReport,
  ProviderAttemptReportSchema,
} from "./provider";

import {
  ArchiveFailedStatusSchema,
  ArchiveGapSchema,
  ArchiveObjectClassSchema,
  ArchiveObjectRecordSchema,
  ArchiveRecordSchema,
  ArchiveStateSchema,
  CaptionFinalitySchema,
  CaptionPacketSchema,
  CaptureReadyStatusSchema,
  ConsultationStateSchema,
  CredentialReferenceSchema,
  DirectionSelectionSchema,
  EgressResultSchema,
  ExternalEffectStateSchema,
  FinalInventorySchema,
  GrpcRawReferenceSchema,
  HttpRawReferenceSchema,
  InterpretationTrackNameSchema,
  InventoryErrorSchema,
  InventorySupplementSchema,
  MagicLinkPurposeSchema,
  NullableStaffRoleSchema,
  ParticipantAttributesSchema,
  ParticipantRoleSchema,
  ParticipantSchema,
  PcmSidecarSchema,
  ProviderAttemptTerminalSchema,
  ProviderErrorSchema,
  ProviderWatermarksSchema,
  RawTransportReferenceSchema,
  RetryDecisionSchema,
  RoomCloseRecordSchema,
  RoomProviderSelectionSchema,
  SameLanguageBypassStatusSchema,
  SameLanguageDirectionSelectionSchema,
  SampleRangeSchema,
  ShutdownStatusSchema,
  StaffRoleSchema,
  StatusPacketSchema,
  SttSelectionSchema,
  TranslatedDirectionSelectionSchema,
  TranslationSelectionSchema,
  TtsSelectionSchema,
  WebSocketRawReferenceSchema,
  WorkerCheckpointSchema,
  WorkerJobMetadataSchema,
  WorkerTerminalRecordSchema,
} from "./consultation";
import { ProviderAttemptReportSchema } from "./provider";

export const CONTRACT_SCHEMAS = {
  ArchiveFailedStatus: ArchiveFailedStatusSchema,
  ArchiveGap: ArchiveGapSchema,
  ArchiveObjectClass: ArchiveObjectClassSchema,
  ArchiveObjectRecord: ArchiveObjectRecordSchema,
  ArchiveRecord: ArchiveRecordSchema,
  ArchiveState: ArchiveStateSchema,
  CaptionFinality: CaptionFinalitySchema,
  CaptionPacket: CaptionPacketSchema,
  CaptureReadyStatus: CaptureReadyStatusSchema,
  CredentialReference: CredentialReferenceSchema,
  ConsultationState: ConsultationStateSchema,
  DirectionSelection: DirectionSelectionSchema,
  EgressResult: EgressResultSchema,
  ExternalEffectState: ExternalEffectStateSchema,
  FinalInventory: FinalInventorySchema,
  GrpcRawReference: GrpcRawReferenceSchema,
  HttpRawReference: HttpRawReferenceSchema,
  InventoryError: InventoryErrorSchema,
  InventorySupplement: InventorySupplementSchema,
  InterpretationTrackName: InterpretationTrackNameSchema,
  MagicLinkPurpose: MagicLinkPurposeSchema,
  NullableStaffRole: NullableStaffRoleSchema,
  ParticipantAttributes: ParticipantAttributesSchema,
  ParticipantRole: ParticipantRoleSchema,
  Participant: ParticipantSchema,
  PcmSidecar: PcmSidecarSchema,
  ProviderAttemptReport: ProviderAttemptReportSchema,
  ProviderAttemptTerminal: ProviderAttemptTerminalSchema,
  ProviderError: ProviderErrorSchema,
  ProviderWatermarks: ProviderWatermarksSchema,
  RawTransportReference: RawTransportReferenceSchema,
  RetryDecision: RetryDecisionSchema,
  RoomCloseRecord: RoomCloseRecordSchema,
  RoomProviderSelection: RoomProviderSelectionSchema,
  SameLanguageBypassStatus: SameLanguageBypassStatusSchema,
  SameLanguageDirectionSelection: SameLanguageDirectionSelectionSchema,
  SampleRange: SampleRangeSchema,
  ShutdownStatus: ShutdownStatusSchema,
  StaffRole: StaffRoleSchema,
  StatusPacket: StatusPacketSchema,
  SttSelection: SttSelectionSchema,
  TranslatedDirectionSelection: TranslatedDirectionSelectionSchema,
  TranslationSelection: TranslationSelectionSchema,
  TtsSelection: TtsSelectionSchema,
  WebSocketRawReference: WebSocketRawReferenceSchema,
  WorkerCheckpoint: WorkerCheckpointSchema,
  WorkerJobMetadata: WorkerJobMetadataSchema,
  WorkerTerminalRecord: WorkerTerminalRecordSchema,
} as const;
