#!/bin/sh
set -eu
. "$(dirname -- "$0")/../deploy/scripts/compose-lib.sh"
load_state
if volume_deletion_requested "$@" && ! compose_help_requested "$@"; then
  confirm_volume_deletion
  compose down --remove-orphans "$@"
  printf '%s\n' 'Persistent volumes removed. Versioned files in .secrets were preserved.'
else
  compose down --remove-orphans "$@"
  printf '%s\n' 'Persistent volumes and .secrets were preserved.'
fi
